# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'Docker  Connection'
  imageRepository: 'syncoboxpanorama'
  containerRegistry: 'webimdocker.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  dockerbuildContext: '$(Build.SourcesDirectory)/'
  tag: '$(Build.BuildNumber)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        dockerfile: $(dockerfilePath)
        buildContext: $(dockerbuildContext)
        arguments: |
         --build-arg NPM_TOKEN=$(NPM_TOKEN)
         -t $(containerRegistry)/$(imageRepository):$(tag)
         -t $(containerRegistry)/$(imageRepository):latest
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
        tags: |
          $(tag)
          latest
    - task: CopyFiles@2
      displayName: copy docker-compose files
      inputs:
        Contents: '**/?(docker-compose.yml|docker-compose.release.yml)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
